# Use postgres/example user/password credentials
version: '3.1'

services:
 
  db:
    image: postgres:14.8
    container_name: ortex_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ortex
    volumes:
      - './data/:/var/lib/postgresql/data/'
      - './init.d/:/docker-entrypoint-initdb.d/'
      - './scripts/:/tmp/scripts/'
    ports:
      - 5432:5432
 
 
